# permissions for end users to view reqauthwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reqauthwatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-jwtwatcher-sdk
    app.kubernetes.io/part-of: operator-jwtwatcher-sdk
    app.kubernetes.io/managed-by: kustomize
  name: reqauthwatcher-viewer-role
rules:
- apiGroups:
  - authorizer.watcher.reqauth.com
  resources:
  - reqauthwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorizer.watcher.reqauth.com
  resources:
  - reqauthwatchers/status
  verbs:
  - get
