# permissions for end users to edit reqauthwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reqauthwatcher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-jwtwatcher
    app.kubernetes.io/part-of: operator-jwtwatcher
    app.kubernetes.io/managed-by: kustomize
  name: reqauthwatcher-editor-role
rules:
- apiGroups:
  - watcher.reqauth.com
  resources:
  - reqauthwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.reqauth.com
  resources:
  - reqauthwatchers/status
  verbs:
  - get
